- name: "Copy backup"
  copy:
  src: "{{ item }}"
  dest: /tmp/backup/{{vol}}.tar.bz2
  with_fileglob:
    - *_{{vol}}.tar.bz2

- name: "Recreate volumes"
  include: volumes.yml
  become: True
  with_items:
    - "{{vol}}"

- name: "Restore from backup"
  shell: |
    docker run --rm -i -v {{ vol }}:/{{vol}} -v /tmp/backup:/backup:ro \
        {{ alpine_image }} \
        sh -c "\
        apk update;\
        apk add -y tar;\
        rm -rf /{{vol}}/* ;\
        tar -C /{{vol}}/ -xjf /backup/{{ vol }}.tar.bz2;"

